### PR TITLE
Upgrade to version 8.0.29

### PR DESCRIPTION
**Pull request by tobijk**
Upgrade from v6 to v8.

### CODE REVIEW

**Comment by nehaljwani** [comment]
The packages `mysql-connector-c` and `mysql-connector-cpp` are different as they provide different libraries and headers. Assuming you are looking for `libmysqlclient.so`, conda-forge generates it using the multiple output recipe of `mysql`.

**Comment by tobijk** [comment]
It says mysql-connector-cpp contains compatible c headers?

**Comment by nehaljwani** [comment]
It provides compatible C headers for [X DevAPI](https://dev.mysql.com/doc/x-devapi-userguide/en/), which is totally different, compared to what `mysql-connector-c` provided.
https://dev.mysql.com/doc/connector-cpp/8.0/en/connector-cpp-apps-general-considerations.html

You can also download and inspect https://cdn.mysql.com//Downloads/Connector-C++/mysql-connector-c++-8.0.29-linux-glibc2.12-x86-64bit.tar.gz

**Comment by tobijk** [comment]
Thanks a lot for intercepting this and for the detailed explanation :)

**Pull request closed without merging**
